name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Backend image
        run: |
          docker build -f backend/Dockerfile -t pranshu02/backend:latest backend
          docker push pranshu02/backend:latest

      - name: Build and push Frontend image
        run: |
          docker build -f nextjsfrontend/Dockerfile -t pranshu02/frontend:latest frontend
          docker push pranshu02/frontend:latest
