name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Backend image
        run: |
          docker build -f backend/Dockerfile -t pranshu02/backend:latest backend
          docker push pranshu02/backend:latest

      - name: Build and push Frontend image
        run: |
          docker build -f nextjsfrontend/Dockerfile -t pranshu02/frontend:latest nextjsfrontend
          docker push pranshu02/frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend backend=pranshu02/backend:latest --record
          kubectl set image deployment/frontend frontend=pranshu02/frontend:latest --record
